# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  CIRCLE_WORKFLOW_ID:
    description: "A very simple command print CIRCLE_WORKFLOW_ID"
    steps:
      - run: echo << $CIRCLE_WORKFLOW_ID >>

defaults: &doc
    docker:
      - image: circleci/node:13.8.0
jobs:
  save_hello_world_output:
  <<: *doc
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
  <<: *doc
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  my_workflow:
    jobs:
      - CIRCLE_WORKFLOW_ID
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
